# Blog global settings
header-img:  # header-img.png 
email: 390517426@qq.com # your email
keyword:  # your keywords

# Navigator of blog
# No need for adding a home page, it is added by default
# Name of icon must exist in Font Awesome
nav: 
  - name: 归档
    url: archives/index.html
    icon: fa-archive
  - name: 留言板
    url: guestbook/index.html
    icon: fa-comment
  - name: 关于
    url: about/index.html
    icon: fa-user
  - name: RSS
    url: atom.xml
    icon: fa-rss-square

# SNS settings
# replace usernames with yours
weibo_username: 
zhihu_username: huang-wen-rui-74
github_username: unnamed42
twitter_username: 
facebook_username: 
linkedin_username: 

# Sidebar settings
sidebar: true
sidebar-about-description: 
sidebar-avatar: /img/avatar.png

# Set to true to use jQuery based off-line search
# This function requires hexo-generator-search
site_search: true

# Recent contents
list_categories: true
recent_posts: true
recent_comments: true

# Disqus settings 
disqus_username: 
# Duoshuo settings
duoshuo_username: unnamed42-github
# Share depends on Comment so can NOT use share only.
# set to false if you want to disable Sharing.
duoshuo_share: false

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
# Format: UA-xxxxxx-xx
ga_track_id:            
ga_domain:

# img CDN path
cdn-url: 

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-post: "?" # you can custom post width and height
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: 

# If you want to show word count, set to true
# This function requires hexo-wordcount
word_count: true

# Set the length of preview text
preview_length: 150

# Featured tag settings
featured-tags: true
# A tag will be featured if the size of it is more than this value
featured-condition-size: 1

# Links
friends:
  - title: Tony
    url: https://tonyzzx.github.io

# Build settings
# if you want to customize anchor. check out line:181 of `post.html`
anchorjs: false
